### ISSUE TITLE
Wrong folder published to npm?

### ISSUE THREAD

**Issue by midgleyc** [androizer/ngx-dynamic-breadcrumb#1]
By [UNPKG](https://unpkg.com/browse/ngx-dynamic-breadcrumb@1.0.7/), it looks like you're publishing `projects/ngx-breadcrumb/` to npm, while you want to publish `dist/ngx-breadcrumb/` to npm.

`projects` contains the raw typescript, while `dist` contains the compiled JS and declaration files.

**Comment by androizer** [comment]
Thanks @midgleyc  for the head-up. But if I publish `dist/ngx-breadcrumb`, the size of the tarball will increase exponentially. Is this intentional while publishing angular packages?

**Comment by midgleyc** [comment]
Yes: this is the [Angular Package Format](https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/preview). You'll note that there are folders for `bundles`, `esm2015`, `fesm2015`: this is your code compiled multiple times for different targets.

If your library is used in an Angular project, Angular won't use all the files: it will pick the most relevant target and ignore the rest.

**Comment by androizer** [comment]
Thanks for explaining. I've read this doc before. But still, the package size increased exponentially is what concerned me. Anyhow, I've published a new build with the `dist` structure.

**Comment by midgleyc** [comment]
Looks good!
