### ISSUE TITLE
allow Angular 12 in peer dependencies

### ISSUE THREAD

**Issue by midgleyc** [androizer/ngx-dynamic-breadcrumb#2]
The [package.json](https://github.com/androizer/ngx-dynamic-breadcrumb/blob/master/projects/ngx-breadcrumb/package.json) currently denies Angular 12 in the peer dependencies, though the project seems to work with it.

Can you extend the allowed versions to allow 12?

I think 13 is going to be breaking due to Ivy changes and View Engine not being supported any more, but 12 seems okay.

**Comment by androizer** [comment]
@midgleyc yea sure. I'll update the build by the weekend.

**Comment by androizer** [comment]
@midgleyc bumped up to support v12. Hence closing the issue.
