### ISSUE TITLE
Upgrade to Angular 13

### ISSUE THREAD

**Issue by midgleyc** [androizer/ngx-dynamic-breadcrumb#3]
We're currently running this on Angular 13, just getting a peer dependency error. So that part is easily fixed.

More involved would be generating an Ivy version, as you're currently only generating for View Engine. That would be more involved, and require a major version update, as earlier versions of Angular (e.g. 9, which you still support) don't support Ivy. At that point I think you may as well go all the way to minimum Angular 13, rxjs 7.

**Comment by androizer** [comment]
Hi @midgleyc,

Thanks for suggesting the change. Should I release a major version that would depreciate the support for legacy View Engine and support for Ivy compatible only with Angular > 12 and RxJs > 6?

**Comment by midgleyc** [comment]
Yes, I think that would be good.

Node 12 also becomes end-of-life at the [end of this month](https://nodejs.org/en/about/releases/), and Angular 13 [supports both 14 and 16](https://gist.github.com/LayZeeDK/c822cc812f75bb07b7c55d07ba2719b3), so you could advance a major node version if that would be convenient.

**Comment by androizer** [comment]
Ok. So I would be pushing the new major version  2.0.0 by the end of this weekend. Anything, in particular, should I take care of especially when releasing Ivy complaint build?

**Comment by midgleyc** [comment]
I don't think so. I can file another issue, or post here, if something in particular doesn't work correctly.

**Comment by androizer** [comment]
Hi @midgleyc,

Just raised a PR for ivy compatible build. This is a prerequisite.
https://github.com/androizer/ngx-dynamic-breadcrumb/pull/6

Can you review this?

Thanks.

**Comment by androizer** [comment]
Hi @midgleyc,

I have made a new release. You can test it out and see if it works fine on your end. For now, closing this issue.

**Comment by midgleyc** [comment]
Looks good, thank you!
